Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,8 +73,11 @@ jobs:
   Install-trivy:  # New reusable job
     runs-on: ubuntu-latest
     needs: Build
+    outputs:
+      trivy-installed: ${{ steps.validate-trivy.outputs.success }}
     steps:
       - name: Install Trivy
+        id: install-trivy
         run: |
           sudo apt-get install wget apt-transport-https gnupg lsb-release
           wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
@@ -83,6 +86,16 @@ jobs:
           sudo apt-get install trivy
           wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
           sudo dpkg -i trivy_0.18.3_Linux-64bit.deb 
+
+      - name: Validate Trivy Installation
+        id: validate-trivy
+        run: |
+          if ! command -v trivy &>/dev/null; then
+            echo "Trivy installation failed!"
+            exit 1
+          fi
+          echo "Trivy successfully installed"
+          echo "::set-output name=success::true"
 
   Trivy-scan:
     runs-on: ubuntu-latest
